name: Multi-EconomyAPI
version: "${pom.version}"
author: onebone
api: ["1.0.0"]
main: me.onebone.multieconomyapi.MultiEconomyAPI

permissions:
  multieconomyapi:
    children:
      multieconomyapi.command:
        children:
          multieconomyapi.command.mymoney:
            default: true
          multieconomyapi.command.topmoney:
            default: true
          multieconomyapi.command.seemoney:
            default: true
          multieconomyapi.command.givemoney:
            default: op
          multieconomyapi.command.takemoney:
            default: op
          multieconomyapi.command.pay:
            default: true
          multieconomyapi.command.setmoney:
            default: op
